NIAEFEUP/nitsig

- bundle-script.js
- content-scripts/src/modules/options/all.js
- css/simpler.css
> popup redesign

- css/simpler.css
Closes #66 
See effect at "Informação Pessoal" Page.
> Smooth scroll

- css/simpler.css
> Fix popup height

- content-scripts/src/modules/initialize.js
Closes #93
Easy fix, just check if the document was found.
> Fix bug when no transaction document is found

- content-scripts/src/index.js
- css/simpler.css
Some pages were broken, like the current account, because the classPage script was causing issues of elements not found.
I take the change to adjust the warning card also.
> Fix pages broken

- background.js
- content-scripts/src/modules/options/some_options.js
Add default value for popup options.
> Fix popup options storage

- content-scripts/src/modules/utilities/pageUtils.js
- content-scripts/src/pages/teacher_page.js
- css/teacherPage.css
Closes #89 
Restores content lost in the previous changes on this page and applies formatting to the remaining sections.
> Fix teacher page fields

- content-scripts/src/modules/icons/index.js
Events on icons were not working on some pages, like this one: https://sigarra.up.pt/feup/pt/it_geral.ver_insc
> Fix icon events

- content-scripts/src/modules/schedule.js
- css/simpler.css
Closes #120, closes #122.
The overlapping classes are still not completely fixed, but they at least look better now.
> Fix schedule style and overlapping classes

- css/icons.css
> Fix icon background in timeline

- content-scripts/src/modules/utilities/sigarra.js
- manifest.js
Mainly because it was breaking the edit profile button
> Fix getUP on new layout

- content-scripts/src/modules/icons/constants.js
- content-scripts/src/modules/icons/index.js
- css/simpler.css
- manifest.js
> Fix multiline information banners

- content-scripts/src/pages/class_page.js
Closes #143 
shows class size near each class
> Show class size

- content-scripts/src/modules/layout.js
- css/simpler.css
Closes #136 
TODO: ~~mark notifications as read and~~ handle pagination
> Show the user's notifications in a popup

- content-scripts/components/HeaderAuthentication.tsx
> Add schedule link to header

- webpack.config.js
> changed klaw file filter

- background.js
- content-scripts/components/Navbar/HeaderAuthentication.tsx
> Fix Notifications Load

- content-scripts/modules/expandable-card.js
- content-scripts/pages/class_page.js
> Fix card expand and class page accordions

- .github/workflows/cd.yml
We changed building in this release, this was missing.
> Update CD release

- .github/workflows/cd.yml
> Add corepack to CD

- .github/workflows/cd.yml
> Add corepack
